### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by ashtefan** [FayzB/Traduction-APKs#1]
Hello FayzB,
I haven't seen any activity on Mi apps lately. Is the project discontinued?
Thanks.

**Comment by FayzB** [comment]
not the project continues sorry for my absence I resume service

**Comment by FayzB** [comment]
Hello here is a link MEGA to have the apps in front premiere
AmazFit-2.5.0.1 with trad values-ro 2.4.0 currently

Link: https://mega.nz/#F!xrQWGByQ!24SHCozc2XLifYkg9nyQZw

**Comment by ashtefan** [comment]
Hello FayzB,
I tried to install the new version but I get the Package corrupted message.
I have updated my translation and if it's not too hard to you, maybe you can rebuild the new version with the updated files to see if the error is from my translation.
Thanks.

**Comment by FayzB** [comment]
Application updated with translations
For the error it is necessary to disconnect the watch then to delete the application.
Install the new version to pair the watch it will resinchronize your data.

Why ?? change of compilation tools and pc

Available version in mega
